/**
 * Generated by scripts/translate-ui.mjs. Committed on purpose.
 *
 * Edit a string here by hand when the machine gets one wrong - the generator
 * leaves anything already present alone, so a correction survives every later
 * run. Delete a key to have it translated again.
 *
 * English is not in here; it is src/i18n/en.ts, which is the source text.
 *
 * Empty until `npm run i18n` is run. Missing keys fall back to English, so the
 * game works in every language today - it is just in English until this file
 * is filled, and that is the intended half-built state rather than a bug.
 */
export const TRANSLATIONS: Record<string, Record<string, string>> = {};
