/**
 * Terrain prop frames in public/terrain/props-v1.webp.
 *
 * GENERATED by tools/skinforge/props.py - do not edit by hand.
 * Re-run the script when art is added or replaced.
 *
 * Frames only. What a prop IS - its class, whether it blocks base
 * placement, its logical footprint in plots - lives in
 * shared/terrainProps.ts, which is written by hand.
 */

export interface AtlasFrame {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const PROP_ATLAS_SRC = '/terrain/props-v1.webp';
export const PROP_ATLAS_W = 2048;
export const PROP_ATLAS_H = 1046;

export const PROP_FRAMES: Record<string, AtlasFrame> = {
  boulder_cluster_a: {x: 684, y: 342, w: 340, h: 274},
  cable_spool_a: {x: 0, y: 0, w: 314, h: 340},
  cargo_container_a: {x: 0, y: 342, w: 340, h: 287},
  cargo_container_b: {x: 1461, y: 0, w: 340, h: 304},
  dry_grass_a: {x: 1368, y: 342, w: 340, h: 271},
  dry_grass_b: {x: 342, y: 866, w: 340, h: 175},
  fuel_drums_a: {x: 777, y: 0, w: 340, h: 332},
  hardy_tree_a: {x: 316, y: 0, w: 330, h: 340},
  hardy_tree_b: {x: 1119, y: 0, w: 340, h: 326},
  hardy_tree_c: {x: 0, y: 631, w: 340, h: 233},
  power_pylon_a: {x: 648, y: 0, w: 127, h: 340},
  power_pylon_b: {x: 342, y: 631, w: 340, h: 233},
  rusted_pipe_run_a: {x: 684, y: 631, w: 340, h: 217},
  sandstone_shelf_a: {x: 1026, y: 866, w: 340, h: 93},
  sandstone_shelf_b: {x: 0, y: 866, w: 340, h: 178},
  scrap_pile_a: {x: 342, y: 342, w: 340, h: 286},
  scrap_pile_b: {x: 1368, y: 631, w: 340, h: 186},
  thorn_brush_a: {x: 1026, y: 342, w: 340, h: 274},
  thorn_brush_b: {x: 684, y: 866, w: 340, h: 149},
  thorn_brush_c: {x: 1026, y: 631, w: 340, h: 215},
};
