/**
 * Iron Dominion Arena on the server: the day's Benchmark Squad, the three
 * attempts, the boards, and the Monday settlement. Rules in shared/arena.ts.
 *
 * Everything settles on read. The Benchmark Squad is generated by the first
 * read of a day; the week is settled by the first read after Monday 00:00
 * RST. Both are PRIMARY KEY rows, so a second first-read changes nothing.
 * An attempt is a fight between two snapshots: nothing of the player's is
 * damaged, spent or marched.
 */
import {
  ARENA_ATTEMPTS_PER_DAY,
  ATTEMPTS_FOR_WEEKLY_REWARD,
  FIELD_CACHE,
  FULL_ENGAGEMENT_BONUS,
  type ScoreBreakdown,
  type WeeklyStanding,
  anonymise,
  bandForRank,
  benchmarkView,
  bootstrapBenchmark,
  lethalityIndex,
  rankStandings,
  scoreAttempt,
  squadPowerOf,
  WARDEN_NAME,
  wardenHardpoints,
} from '../shared/arena';
import {type CombatantSpec, resolve} from '../shared/combat';
import {type StoredBattle, parseStoredAttempt, storedBattle} from '../shared/arenaReplay';
import {hashSeed, seeded} from '../shared/exercises';
import {dailyWindow, describeReward, seasonPhase, weeklyWindow} from '../shared/season1Ops';
import {ARENA_SYSTEMS_KEY} from './combatSystems';
import {grantReward} from './dailyOps';
import {arenaForce} from './arenaSquad';

interface DayRow {
  world_id: number;
  day_key: string;
  week_key: string;
  benchmark: string;
  source_attempt_id: string | null;
}

interface AttemptRow {
  id: string;
  player_id: string;
  day_key: string;
  week_key: string;
  n: number;
  squad: string;
  snapshot: string;
  seed: number;
  score: number;
  breakdown: string;
  outcome: string;
  battle_id: string | null;
  created_at: number;
}

function parseUnits(raw: string): CombatantSpec[] {
  try {
    const v = JSON.parse(raw) as CombatantSpec[];
    return Array.isArray(v) ? v : [];
  } catch {
    return [];
  }
}

/* -------------------------------------------------------------------------- */
/* The day's Benchmark Squad                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Today's benchmark for a world, generating it if this is the first read.
 * Source: the previous day's attempt snapshot with the highest lethality
 * (ties: power, then attempt id), anonymised. None: the bootstrap.
 */
export async function ensureBenchmark(db: D1Database, worldId: number, now: number): Promise<{units: CombatantSpec[]; row: DayRow}> {
  const day = dailyWindow(now);
  const existing = await db
    .prepare(`SELECT * FROM arena_days WHERE world_id = ?1 AND day_key = ?2`)
    .bind(worldId, day.key)
    .first<DayRow>();
  if (existing) return {units: parseUnits(existing.benchmark), row: existing};

  const yesterday = dailyWindow(day.startsAt - 1).key;
  const prior = await db
    .prepare(`SELECT id, snapshot FROM arena_attempts WHERE world_id = ?1 AND day_key = ?2`)
    .bind(worldId, yesterday)
    .all<{id: string; snapshot: string}>();
  let best: {id: string; units: CombatantSpec[]; lethality: number; power: number} | null = null;
  for (const r of prior.results ?? []) {
    const units = parseUnits(r.snapshot);
    if (units.length === 0) continue;
    const lethality = lethalityIndex(units);
    const power = squadPowerOf(units);
    if (
      !best ||
      lethality > best.lethality ||
      (lethality === best.lethality && (power > best.power || (power === best.power && r.id < best.id)))
    ) {
      best = {id: r.id, units, lethality, power};
    }
  }
  const {week} = seasonPhase(now);
  const roll = seeded(hashSeed(`arena:${worldId}:${day.key}`));
  const units = best ? anonymise(best.units, roll) : bootstrapBenchmark(week);
  await db
    .prepare(
      `INSERT OR IGNORE INTO arena_days (world_id, day_key, week_key, benchmark, source_attempt_id, created_at)
       VALUES (?1, ?2, ?3, ?4, ?5, ?6)`,
    )
    .bind(worldId, day.key, weeklyWindow(now).key, JSON.stringify(units), best?.id ?? null, now)
    .run();
  const made = await db
    .prepare(`SELECT * FROM arena_days WHERE world_id = ?1 AND day_key = ?2`)
    .bind(worldId, day.key)
    .first<DayRow>();
  return {units: made ? parseUnits(made.benchmark) : units, row: made ?? {world_id: worldId, day_key: day.key, week_key: weeklyWindow(now).key, benchmark: JSON.stringify(units), source_attempt_id: best?.id ?? null}};
}

/* -------------------------------------------------------------------------- */
/* An attempt                                                                 */
/* -------------------------------------------------------------------------- */

export type AttemptResult =
  | {ok: true; attempt: AttemptView; fieldCache: boolean; fullEngagement: boolean}
  | {ok: false; error: string};

export type {StoredBattle} from '../shared/arenaReplay';

export interface AttemptView {
  id: string;
  n: number;
  squad: string;
  score: number;
  outcome: string;
  breakdown: ScoreBreakdown | null;
  units: CombatantSpec[];
  battle: StoredBattle | null;
  createdAt: number;
  dayKey: string;
}

function parseAttempt(r: AttemptRow): AttemptView {
  const {breakdown, battle} = parseStoredAttempt(r.breakdown, WARDEN_NAME, r.seed);
  return {
    id: r.id,
    n: r.n,
    squad: r.squad,
    score: r.score,
    outcome: r.outcome,
    breakdown,
    units: parseUnits(r.snapshot),
    battle,
    createdAt: r.created_at,
    dayKey: r.day_key,
  };
}

/** One stored attempt, for the report and the replay. Only the owner's. */
export async function readAttempt(db: D1Database, playerId: string, id: string): Promise<AttemptView | null> {
  const row = await db.prepare(`SELECT * FROM arena_attempts WHERE id = ?1 AND player_id = ?2`).bind(id, playerId).first<AttemptRow>();
  return row ? parseAttempt(row) : null;
}

/** The player's attempts, newest first, for the Reports screen. */
export async function listAttempts(db: D1Database, playerId: string, limit = 30): Promise<AttemptView[]> {
  const rows = await db
    .prepare(`SELECT * FROM arena_attempts WHERE player_id = ?1 ORDER BY created_at DESC LIMIT ?2`)
    .bind(playerId, limit)
    .all<AttemptRow>();
  return (rows.results ?? []).map(parseAttempt);
}

export async function makeAttempt(
  db: D1Database,
  playerId: string,
  username: string,
  worldId: number,
  away: Set<string>,
  now: number,
  newId: () => string,
): Promise<AttemptResult> {
  const day = dailyWindow(now);
  const week = weeklyWindow(now);
  const {phase} = seasonPhase(now);
  if (phase === 'pre') return {ok: false, error: 'The Arena opens with Season 1.'};
  if (phase === 'offseason') return {ok: false, error: 'The Arena is closed for the offseason.'};

  const done = await db
    .prepare(`SELECT n FROM arena_attempts WHERE player_id = ?1 AND day_key = ?2 ORDER BY n`)
    .bind(playerId, day.key)
    .all<{n: number}>();
  const used = (done.results ?? []).length;
  if (used >= ARENA_ATTEMPTS_PER_DAY) return {ok: false, error: 'No attempts left today. Three more at 00:00 RST.'};

  const chosen = await arenaForce(db, playerId, away, now);
  if (!chosen.ok) return chosen;
  const force = {squad: ARENA_SYSTEMS_KEY, units: chosen.force.units, power: chosen.force.power};

  const {units: benchmark} = await ensureBenchmark(db, worldId, now);
  const id = newId();
  const seed = Math.abs(hashSeed(`${id}:${playerId}:${day.key}`)) % 2147483647;
  // Resolved here, once, before anything is shown. What is stored is the
  // whole fight: the replay plays these events and can change nothing.
  const result = resolve({name: username, units: force.units}, {name: WARDEN_NAME, units: benchmark}, seed);
  const breakdown = scoreAttempt(result);
  const n = used + 1;
  const stored = storedBattle(result, WARDEN_NAME, benchmark, seed);

  const inserted = await db
    .prepare(
      `INSERT OR IGNORE INTO arena_attempts
         (id, player_id, world_id, day_key, week_key, n, squad, snapshot, seed, score, breakdown, outcome, battle_id, created_at)
       VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, NULL, ?13)`,
    )
    .bind(id, playerId, worldId, day.key, week.key, n, force.squad, JSON.stringify(force.units), seed, breakdown.score, JSON.stringify({...breakdown, ...stored}), result.outcome, now)
    .run();
  // Two taps at once: the UNIQUE (player, day, n) lets one through.
  if (!(inserted.meta.changes ?? 0)) return {ok: false, error: 'That attempt already went through. Refresh.'};

  // The Field Cache on the first settled attempt of the day, the Full
  // Engagement bonus on the third - each once, by grant key.
  const fieldCache = n === 1 && (await grantReward(db, playerId, `arena-field:${playerId}:${day.key}`, 'arena-field-cache', FIELD_CACHE, `Arena Field Cache · ${describeReward(FIELD_CACHE)}`, now));
  const fullEngagement =
    n === ARENA_ATTEMPTS_PER_DAY &&
    (await grantReward(db, playerId, `arena-full:${playerId}:${day.key}`, 'arena-full-engagement', FULL_ENGAGEMENT_BONUS, `Arena Full Engagement · ${describeReward(FULL_ENGAGEMENT_BONUS)}`, now));

  return {
    ok: true,
    attempt: {
      id,
      n,
      squad: force.squad,
      score: breakdown.score,
      outcome: result.outcome,
      breakdown,
      units: force.units,
      battle: stored,
      createdAt: now,
      dayKey: day.key,
    },
    fieldCache,
    fullEngagement,
  };
}

/* -------------------------------------------------------------------------- */
/* Boards                                                                     */
/* -------------------------------------------------------------------------- */

export interface BoardRow {
  playerId: string;
  username: string;
  score: number;
  best: number;
  attempts: number;
  reachedAt: number;
  rank: number;
}

/** Daily board: each player's best attempt today, ranked. */
export async function dailyBoard(db: D1Database, worldId: number, dayKey: string, limit = 50): Promise<BoardRow[]> {
  const rows = await db
    .prepare(
      `SELECT a.player_id AS playerId, p.username AS username, MAX(a.score) AS best, COUNT(*) AS attempts,
              MIN(CASE WHEN a.score = (SELECT MAX(b.score) FROM arena_attempts b WHERE b.player_id = a.player_id AND b.day_key = a.day_key) THEN a.created_at END) AS reachedAt
         FROM arena_attempts a JOIN players p ON p.id = a.player_id
        WHERE a.world_id = ?1 AND a.day_key = ?2
        GROUP BY a.player_id`,
    )
    .bind(worldId, dayKey)
    .all<{playerId: string; username: string; best: number; attempts: number; reachedAt: number}>();
  const standings: WeeklyStanding[] = (rows.results ?? []).map((r) => ({...r, score: r.best}));
  return rankStandings(standings)
    .slice(0, limit)
    .map((r, i) => ({...r, rank: i + 1}));
}

/** Weekly board: sum of each player's daily bests this week, ranked. */
export async function weeklyStandings(db: D1Database, worldId: number, weekKey: string): Promise<WeeklyStanding[]> {
  const rows = await db
    .prepare(
      `SELECT player_id AS playerId, day_key AS dayKey, MAX(score) AS best, COUNT(*) AS attempts,
              MIN(CASE WHEN score = (SELECT MAX(b.score) FROM arena_attempts b WHERE b.player_id = a.player_id AND b.day_key = a.day_key) THEN created_at END) AS reachedAt
         FROM arena_attempts a
        WHERE world_id = ?1 AND week_key = ?2
        GROUP BY player_id, day_key`,
    )
    .bind(worldId, weekKey)
    .all<{playerId: string; dayKey: string; best: number; attempts: number; reachedAt: number}>();
  const byPlayer = new Map<string, WeeklyStanding>();
  for (const r of rows.results ?? []) {
    const cur = byPlayer.get(r.playerId) ?? {playerId: r.playerId, username: '', score: 0, best: 0, attempts: 0, reachedAt: 0};
    cur.score += r.best;
    cur.best = Math.max(cur.best, r.best);
    cur.attempts += r.attempts;
    cur.reachedAt = Math.max(cur.reachedAt, r.reachedAt);
    byPlayer.set(r.playerId, cur);
  }
  const ids = [...byPlayer.keys()];
  for (let i = 0; i < ids.length; i += 90) {
    const chunk = ids.slice(i, i + 90);
    const names = await db
      .prepare(`SELECT id, username FROM players WHERE id IN (${chunk.map((_, j) => `?${j + 1}`).join(',')})`)
      .bind(...chunk)
      .all<{id: string; username: string}>();
    for (const n of names.results ?? []) {
      const s = byPlayer.get(n.id);
      if (s) s.username = n.username;
    }
  }
  return rankStandings([...byPlayer.values()]);
}

/* -------------------------------------------------------------------------- */
/* Monday settlement                                                          */
/* -------------------------------------------------------------------------- */

/**
 * Settle every week that has closed and is not yet settled for this world.
 * Ranks are frozen from the attempts table; each reward is one grant keyed
 * by (week, player), so the whole settlement can run twice and pay once.
 * Rank rewards need ATTEMPTS_FOR_WEEKLY_REWARD settled attempts that week.
 */
export async function settleClosedWeeks(db: D1Database, worldId: number, now: number): Promise<number> {
  const current = weeklyWindow(now).key;
  const open = await db
    .prepare(
      `SELECT DISTINCT a.week_key AS weekKey FROM arena_attempts a
        WHERE a.world_id = ?1 AND a.week_key != ?2
          AND NOT EXISTS (SELECT 1 FROM arena_weeks w WHERE w.world_id = a.world_id AND w.week_key = a.week_key)`,
    )
    .bind(worldId, current)
    .all<{weekKey: string}>();
  let settled = 0;
  for (const {weekKey} of open.results ?? []) {
    const standings = await weeklyStandings(db, worldId, weekKey);
    let rank = 0;
    for (const s of standings) {
      rank += 1;
      if (s.attempts < ATTEMPTS_FOR_WEEKLY_REWARD) continue;
      const band = bandForRank(rank);
      await grantReward(
        db,
        s.playerId,
        `arena-week:${weekKey}:${s.playerId}`,
        'arena-weekly-rank',
        band.reward,
        `Arena week ${weekKey} · rank ${rank} (band ${band.label}) · ${describeReward(band.reward)}${band.badge ? ` · badge: ${band.badge}` : ''}`,
        now,
      );
    }
    await db
      .prepare(`INSERT OR IGNORE INTO arena_weeks (world_id, week_key, settled_at, ranked) VALUES (?1, ?2, ?3, ?4)`)
      .bind(worldId, weekKey, now, standings.length)
      .run();
    settled += 1;
  }
  return settled;
}

/* -------------------------------------------------------------------------- */
/* The screen                                                                 */
/* -------------------------------------------------------------------------- */

export async function arenaView(db: D1Database, playerId: string, worldId: number, away: Set<string>, now: number) {
  const day = dailyWindow(now);
  const week = weeklyWindow(now);
  const {week: seasonWeek, phase} = seasonPhase(now);
  await settleClosedWeeks(db, worldId, now);
  const [{units: benchmark}, mine, daily, weekly, force] = await Promise.all([
    ensureBenchmark(db, worldId, now),
    db
      .prepare(`SELECT * FROM arena_attempts WHERE player_id = ?1 AND day_key = ?2 ORDER BY n`)
      .bind(playerId, day.key)
      .all<AttemptRow>(),
    dailyBoard(db, worldId, day.key),
    weeklyStandings(db, worldId, week.key),
    arenaForce(db, playerId, away, now),
  ]);
  const attempts = (mine.results ?? []).map(parseAttempt);
  const weeklyRanked = weekly.map((s, i) => ({...s, rank: i + 1}));
  const myWeekly = weeklyRanked.find((s) => s.playerId === playerId) ?? null;
  const myDaily = daily.find((s) => s.playerId === playerId) ?? null;
  const lastWeek = await db
    .prepare(`SELECT settled_at AS at, ranked FROM arena_weeks WHERE world_id = ?1 ORDER BY settled_at DESC LIMIT 1`)
    .bind(worldId)
    .first<{at: number; ranked: number}>();
  return {
    phase,
    seasonWeek,
    dayKey: day.key,
    resetAt: day.resetAt,
    closesAt: week.resetAt,
    attemptsUsed: attempts.length,
    attemptsPerDay: ARENA_ATTEMPTS_PER_DAY,
    force: force.ok ? {squad: ARENA_SYSTEMS_KEY, power: force.force.power, units: force.force.units.map((u) => ({assetId: u.assetId, level: u.level, slot: u.slot ?? 0}))} : null,
    forceBlocked: force.ok ? null : force.error,
    benchmark: {units: benchmarkView(benchmark), power: squadPowerOf(benchmark), hardpoints: wardenHardpoints(benchmark), name: WARDEN_NAME},
    attempts,
    daily: daily.map(({playerId: _p, ...r}) => r),
    myDaily: myDaily ? {rank: myDaily.rank, best: myDaily.best} : null,
    weekly: weeklyRanked.slice(0, 100).map(({playerId: _p, ...r}) => r),
    myWeekly: myWeekly ? {rank: myWeekly.rank, score: myWeekly.score, attempts: myWeekly.attempts} : null,
    lastSettlement: lastWeek ?? null,
  };
}
